import Foundation
import FoundationModels

/// Foundation Models Framework を使用して予定を生成する
class AICalendarGenerator {
  static let shared = AICalendarGenerator()

  private let analyzer = UserProfileAnalyzer.shared
  private let predictor = EventPredictor.shared

  // モデルへのセッションを保持（文脈維持のためだが、今回は単発生成）
  private var model: SystemLanguageModel { .default }

  struct GeneratedEvent {
    let title: String
    let category: String
    let duration: TimeInterval
    let notes: String
  }

  /// 指定された日時に対して、最適な予定を生成する (Async)
  func generateEvent(for date: Date) async -> GeneratedEvent? {
    // 1. Core ML: 時系列データからのカテゴリ予測
    guard let predictedCategory = predictor.predictCategory(for: date) else {
      return nil
    }

    // 2. Profile: ユーザーの嗜好データの取得
    let profile = analyzer.loadProfile()

    // 3. Foundation Model: 生成
    // プロンプトの構築
    let prompt = """
      あなたはユーザーの生活を彩るAIアシスタントです。
      以下の情報を元に、カレンダー登録用の「魅力的な予定のタイトル」を1つだけ生成してください。

      【条件】
      - カテゴリ: \(predictedCategory)
      - ユーザーの興味: \(profile.interests.joined(separator: ", "))
      - Vibe: \(profile.vibeDescription)
      - 日時: \(date.formatted())

      【出力形式】
      タイトルのみ（例: "カフェで読書", "ジムでトレーニング"）
      余計な説明は不要です。
      """

    do {
      // モデルセッションの作成 (推測: SystemLanguageModel自体ではなくSessionを使う)
      let session = LanguageModelSession(model: model)

      // 生成実行
      let response = try await session.respond(to: prompt)
      let title = response.content.trimmingCharacters(in: CharacterSet.whitespacesAndNewlines)

      // 簡易的な時間推定 (キーワードに基づく補助ロジックは維持)
      var duration: TimeInterval = 3600
      if title.contains("映画") || title.contains("サウナ") || title.contains("ディナー") {
        duration = 7200
      }

      return GeneratedEvent(
        title: title,
        category: predictedCategory,
        duration: duration,
        notes:
          "Generated by Apple Foundation Models\nBased on: \(predictedCategory) & \(profile.interests.prefix(3).joined(separator: ","))"
      )
    } catch {
      print("Foundation Model Generation Error: \(error)")
      return nil
    }
  }
}
